-- IPMP MySQL / TDSQL-C 回滚迁移
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS user_ai_configs;
DROP TABLE IF EXISTS weekly_reports;
DROP TABLE IF EXISTS work_logs;
DROP TABLE IF EXISTS requirements;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;
